# nix/targets.nix
# TODO: in the future we need hermetic zig builds
{
  pkgs,
  zig,
  cudaPackages,
  gccHost,
  src,
  cudaArchitectures,
  zigradExternalSdk,
}: let
  cudaArchStr = pkgs.lib.concatStringsSep ";" cudaArchitectures;

  colors = {
    yellow = "\\033[33m";
    reset = "\\033[0m";
  };
in {
  # group targets explicitly, can extend this
  targets = {
    zigrad-m4 = rec {
      build = pkgs.stdenvNoCC.mkDerivation {
        pname = "zigrad-m4";
        version = "0.1";
        inherit src;

        nativeBuildInputs = [
          zig.hook
          pkgs.autoAddDriverRunpath
        ];

        buildInputs = [
          zigradExternalSdk
        ];

        zigBuildFlags = [
          "-Doptimize=ReleaseSafe"
          "-Dsdk=${zigradExternalSdk}"
        ];

        postFixup = ''
          # fixupPhase runs `patchelf --shrink-rpath` which will remove the /run/opengl-driver/lib RPATH entry
          #   so we need this so we can load cuda driver on nixos.
          addDriverRunpath "$out/bin/zigrad-pjrt-m4"
        '';

        # tests
        # dontUseZigCheck = true;

        meta.mainProgram = "zigrad-pjrt-m4";
      };

      run = pkgs.writeShellScriptBin "zigrad-m4" ''
        if [ "''${NIX_ENFORCE_NO_NATIVE:-0}" = "1" ]; then
          printf "${colors.yellow}WARNING:${colors.reset} NIX_ENFORCE_NO_NATIVE=1 (no native CPU tuning).\n"
        fi
        export ZG_EXTERNAL_SDK_ROOT="${zigradExternalSdk}"
        export PJRT_PLUGIN_PATH="$ZG_EXTERNAL_SDK_ROOT/runtime/xla/pjrt/c/pjrt_c_api_gpu_plugin.so"
        export XLA_FLAGS="--xla_gpu_cuda_data_dir=${zigradExternalSdk}/runtime/nvidia"
        exec ${build}/bin/zigrad-pjrt-m4 "$@"
      '';
    };

    # Editor integration targets ============================================================
    editor = {
      clangd = pkgs.writeShellScriptBin "gen-clangd" ''
          set -euo pipefail

          root="$(${pkgs.lib.getExe pkgs.git} rev-parse --show-toplevel)"
          echo "Generating .clangd root=$root"

          tmp="$(mktemp)"

          cat > "$tmp" <<EOF
        CompileFlags:
          CompilationDatabase: build
          Add:
            - -I${cudaPackages.cudatoolkit}/include
            - -xcuda
            - --cuda-path=${cudaPackages.cudatoolkit}
            - --no-cuda-version-check
          Remove:
            - -forward-unknown-to-host-compiler

        Diagnostics:
          UnusedIncludes: None
          MissingIncludes: None
        EOF

          mv "$tmp" "$root/.clangd"
          echo "Wrote $root/.clangd"
      '';

      nvim = pkgs.writeShellScriptBin "gen-nvim" ''
        set -euo pipefail

        root="$(git rev-parse --show-toplevel)"
        cd "$root"

        echo "Generating .nvim.local.lua"
        tmp="$(mktemp)"
        cat > "$tmp" <<EOF
        -- generated by nix/targets.nix. do not edit.

        vim.lsp.config["zls"] = {
          cmd = { "${pkgs.zls}/bin/zls" },
          root_marker = { "build.zig", ".git" },
          filetypes = { "zig" },
        }

        vim.lsp.enable("zls")
        EOF

        mv "$tmp" "$root/.nvim.local.lua"
        echo "Wrote $root/.nvim.local.lua"
      '';

      all = pkgs.writeShellScriptBin "gen-editor" ''
        set -e
        ${pkgs.lib.getExe pkgs.git} rev-parse --show-toplevel >/dev/null
        nix run .#gen-clangd
        nix run .#gen-nvim
      '';
    };
  };
}
