# nix/targets.nix
{ pkgs, cudaPackages, gccHost, nixglhost, src, cudaArchitectures }:
let
  cudaArchStr = pkgs.lib.concatStringsSep ";" cudaArchitectures;

  colors = {
    yellow = "\\033[33m";
    reset = "\\033[0m";
  };
in
{
  # group targets explicitly, can extend this
  targets = {
    main = rec {
      # hermetic build target: no host driver needed
      build = pkgs.stdenvNoCC.mkDerivation {
        pname = "main";
        version = "0.1";
        inherit src;

        nativeBuildInputs = [
          pkgs.cmake
          pkgs.gnumake
          cudaPackages.cudatoolkit
          gccHost
        ];

        configurePhase = ''
          cmake -B build -S . \
            -DCMAKE_C_COMPILER=${gccHost}/bin/gcc \
            -DCMAKE_CXX_COMPILER=${gccHost}/bin/g++ \
            -DCMAKE_CUDA_COMPILER=${cudaPackages.cudatoolkit}/bin/nvcc \
            -DCMAKE_CUDA_HOST_COMPILER=${gccHost}/bin/g++ \
            -DCMAKE_CUDA_ARCHITECTURES=${cudaArchStr} \
            -DCMAKE_BUILD_TYPE=Release
        '';

        buildPhase = ''
          cmake --build build -j
        '';

        installPhase = ''
          mkdir -p $out/bin
          # keep output names stable for tooling
          cp build/programs/main $out/bin/main
        '';
      };

      # run target: explicitly impure (host driver stack) via nixglhost wrapper
      run = pkgs.writeShellScriptBin "main" ''
        if [ "''${NIX_ENFORCE_NO_NATIVE:-0}" = "1" ]; then
          printf "${colors.yellow}WARNING:${colors.reset} NIX_ENFORCE_NO_NATIVE=1 (no native CPU tuning).\n"
        fi

        # if i understand correctly, we should prefer wrapping the binary rather than global LD_LIBRARY_PATH injection.
        # nix-gl-host docs call -p a footgun, wrapping is recommended.
        exec ${nixglhost}/bin/nixglhost ${build}/bin/main "$@"
      '';
    };

    # thinking that zig+cuda projects can add a parallel group. e.g.,
    # zig = {
    #   build = pkgs.stdenvNoCC.mkDerivation { ... zig build ... };
    #   run = pkgs.writeShellScriptBin "zig-app" '' exec ${nixglhost}/bin/nixglhost ${build}/bin/zig-app "$@" '';
    # };

    # Editor integration targets ============================================================
    editor = {
      clangd = pkgs.writeShellScriptBin "gen-clangd" ''
          set -euo pipefail

          root="$(${pkgs.lib.getExe pkgs.git} rev-parse --show-toplevel)"
          echo "Generating .clangd root=$root"

          tmp="$(mktemp)"

          cat > "$tmp" <<EOF
        CompileFlags:
          CompilationDatabase: build
          Add:
            - -I${cudaPackages.cudatoolkit}/include
            - -xcuda
            - --cuda-path=${cudaPackages.cudatoolkit}
            - --no-cuda-version-check
          Remove:
            - -forward-unknown-to-host-compiler

        Diagnostics:
          UnusedIncludes: None
          MissingIncludes: None
        EOF

          mv "$tmp" "$root/.clangd"
          echo "Wrote $root/.clangd"
      '';


      nvim = pkgs.writeShellScriptBin "gen-nvim" ''
        set -euo pipefail

        root="$(git rev-parse --show-toplevel)"
        cd "$root"

        echo "Generating .nvim.local.lua"
        tmp="$(mktemp)"
        cat > "$tmp" <<EOF
        -- generated by nix/targets.nix. do not edit.

        vim.lsp.config["zls"] = {
          cmd = { "${pkgs.zls}/bin/zls" },
          root_marker = { "build.zig", ".git" },
          filetypes = { "zig" },
        }

        vim.lsp.enable("zls")
        EOF

        mv "$tmp" "$root/.nvim.local.lua"
        echo "Wrote $root/.nvim.local.lua"
      '';

      all = pkgs.writeShellScriptBin "gen-editor" ''
        set -e
        ${pkgs.lib.getExe pkgs.git} rev-parse --show-toplevel >/dev/null
        nix run .#gen-clangd
        nix run .#gen-nvim
      '';
    };
  };
}
