# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  RED:
    sh: tput setaf 1
  RSYNC_BASE: >-
    rsync -avz
    -e "{{.RSYNC_SSH | default "ssh"}}"
    --checksum
    --no-perms
    --no-owner
    --no-group
    --no-times
    --filter=':- .rsync-filter'

dotenv: [".env"]
env:
  PJRT_PLUGIN_PATH: result/runtime/jax_plugins/xla_cuda13/xla_cuda_plugin.so
  # sh: realpath zig-out/runtime/jax_plugins/xla_cuda13/xla_cuda_plugin.so

tasks:
  _pjrt:
    internal: true
    silent: true
    cmd: |
      if [ ! -f "$PJRT_PLUGIN_PATH" ]; then
        echo "{{.RED}}PJRT_PLUGIN_PATH=$PJRT_PLUGIN_PATH doesnt exist. May need to materialize it w nix or set PJRT_PLUGIN_PATH yourself"
      fi

  sdk:
    cmds:
      - nix build .#zigrad-external-sdk --impure {{.CLI_ARGS}}

  build:
    cmd: zig build

  test:
    cmd: zig build test

  m2:
    deps: [_pjrt, build]
    cmd: ./zig-out/bin/zigrad-pjrt-m2

  m2-fusion:
    deps: [_pjrt, build]
    cmd: ./zig-out/bin/zigrad-pjrt-m2-fusion

  m4:
    deps: [_pjrt, build]
    cmd: ./zig-out/bin/zigrad-pjrt-m4

  m4-custom:
    deps: [_pjrt, build]
    cmd: ./zig-out/bin/zigrad-pjrt-m4-custom

  sync:push:
    desc: "Sync local -> remote (no deletes)"
    cmds:
      - |
        {{.RSYNC_BASE}} {{.CLI_ARGS}} --progress ./ {{.REMOTE}}/
    requires:
      vars: [REMOTE]

  sync:pull:
    desc: "Sync remote -> local (no deletes)"
    cmds:
      - |
        {{.RSYNC_BASE}} {{.CLI_ARGS}} --progress {{.REMOTE}}:/ ./
    requires:
      vars: [REMOTE]

  sync:push:mirror:
    desc: "Mirror local -> remote (DELETES remote files)"
    cmds:
      - |
        {{.RSYNC_BASE}} {{.CLI_ARGS}} --progress --delete ./ {{.REMOTE}}/
    requires:
      vars: [REMOTE]

  sync:push:dry:
    desc: "Dry-run local -> remote (optional verbose output)"
    vars:
      VERBOSE: '{{.VERBOSE | default "off"}}'
      RSYNC_VERBOSE_FLAGS: >-
        {{if eq .VERBOSE "on"}}--itemize-changes --human-readable{{end}}
    requires:
      vars:
        - REMOTE
        - name: VERBOSE
          enum: [off, on]
    cmds:
      - |
        {{.RSYNC_BASE}} --dry-run {{.RSYNC_VERBOSE_FLAGS}} ./ {{.REMOTE}}/

  nix-ccache-setup:
    cmds:
      - sudo mkdir -m0770 -p /nix/var/cache/ccache
      - sudo chown --reference=/nix/store /nix/var/cache/ccache
      - |
        before=$(stat -c %Y /etc/nix/nix.custom.conf)
        sudo sed -i '/^extra-sandbox-paths = \/nix\/var\/cache\/ccache$/!{
          $a\
        extra-sandbox-paths = /nix/var/cache/ccache
        }' /etc/nix/nix.custom.conf
        after=$(stat -c %Y /etc/nix/nix.conf)
        [ "$before" != "$after" ] && echo "nix conf changed, restart daemon."
