VERSION 0.8
deps:
    FROM debian:bookworm-slim
    ENV DEBIAN_FRONTEND=noninteractive
    ENV DEBCONF_NONINTERACTIVE_SEEN true
    RUN apt-get update && apt-get install -y \
        python3 python3-dev python3-pip wget \
        && rm -rf /var/lib/apt/lists/*
    WORKDIR /app
    RUN pip3 install --break-system-packages numpy torch --index-url https://download.pytorch.org/whl/cpu
    ENV BASE_ROOT=$(python3 -c 'import sys, pathlib; print(pathlib.Path(sys.base_prefix).resolve())')
    ENV PYVER=$(python3 -c 'import sys; print(f"python{sys.version_info.major}.{sys.version_info.minor}")')
    ENV INCL=$BASE_ROOT/include/$PYVER
    ENV LIBDIR=$BASE_ROOT/lib
    ENV LIBNAME=python${PYVER#python}
    ENV PYTHONHOME=$BASE_ROOT
    # ENV PYTHONPATH=venv/lib/$PYVER/site-packages
    ENV LD_LIBRARY_PATH=$BASE_ROOT/lib

build-c:
    FROM +deps
    COPY embed_python.c .
    RUN gcc embed_python.c -o embed_python -I"$INCL" -L"$LIBDIR" -l"$LIBNAME"
    CMD ["./embed_python"]
    SAVE IMAGE embed-python:latest

ZIG:
    FUNCTION
    ARG ZIG_VERSION=0.14.0
    ARG INSTALL_PATH=/usr/local
    ARG BINARY_LINK_PATH=/usr/local/bin
    RUN ARCH=$(uname -m) && \
        DOWNLOAD_URL="https://ziglang.org/download/${ZIG_VERSION}/zig-linux-${ARCH}-${ZIG_VERSION}.tar.xz" && \
        wget -q "$DOWNLOAD_URL" && \
        tar -xf "zig-linux-${ARCH}-${ZIG_VERSION}.tar.xz" && \
        mkdir -p "${INSTALL_PATH}" && \
        mv "zig-linux-${ARCH}-${ZIG_VERSION}" "${INSTALL_PATH}/zig" && \
        mkdir -p "${BINARY_LINK_PATH}" && \
        ln -s "${INSTALL_PATH}/zig/zig" "${BINARY_LINK_PATH}/zig" && \
        rm "zig-linux-${ARCH}-${ZIG_VERSION}.tar.xz"

build-zig:
    FROM +deps
    DO +ZIG
    COPY embed_python.zig .
    COPY python.zig .
    RUN zig build-exe embed_python.zig -lc -I"$INCL" -L"$LIBDIR" -l"$LIBNAME"
    SAVE ARTIFACT embed_python

build:
    FROM +deps
    COPY +build-zig/embed_python .
    CMD ["./embed_python"]
    SAVE IMAGE embed-pythonz:latest

build-file-zig:
  FROM +deps
  DO +ZIG
  COPY embed_python.zig .
  COPY python.zig .
  COPY build.zig .
  RUN zig build
  SAVE ARTIFACT ./zig-out/bin/main AS LOCAL ./zig-out/bin/main


build-local:
  LOCALLY
  ENV BASE_ROOT=$(python3 -c 'import sys, pathlib; print(pathlib.Path(sys.base_prefix).resolve())')
  ENV PYVER=$(python3 -c 'import sys; print(f"python{sys.version_info.major}.{sys.version_info.minor}")')
  ENV INCL=$BASE_ROOT/include/$PYVER
  ENV LIBDIR=$BASE_ROOT/lib
  ENV LIBNAME=python${PYVER#python}
  # ENV PYTHONHOME=$BASE_ROOT
  # ENV LD_LIBRARY_PATH=$BASE_ROOT/lib
  RUN zig build-exe embed_python.zig -lc -I"$INCL" -L"$LIBDIR" -l"$LIBNAME"

run:
    FROM +build
    RUN ./embed_python
