//! CUDA-specific TVM support.
//!
//! Handles CUDA tensor intrinsics loading and CUDA module building.
//! Intrinsics are pre-serialized by scripts/generate_cuda_intrinsics.py.

const std = @import("std");
const c = @import("../ffi/tvm/c.zig");
const api = @import("../ffi/tvm/api.zig");

const Value = api.Value;

const log = std.log.scoped(.@"zg/tvm_cuda");

/// Track whether CUDA intrinsics have been loaded.
/// NOTE: this global is not thread-safe, consider using an atomic or mutex if load_intrinsics
///  may be called from multiple threads.
var intrinsics_loaded: bool = false;

/// Load and register CUDA tensor intrinsics from pre-serialized JSON files.
///
/// This function loads 89 CUDA tensor intrinsics (WMMA, MMA, etc.) required
/// for CUDA MetaSchedule auto-tuning. The intrinsics are pre-generated by
/// scripts/generate_cuda_intrinsics.py and stored as JSON files.
///
/// Safe to call multiple times - only loads once.
/// Must be called after TVM compiler is loaded.
pub fn load_intrinsics(allocator: std.mem.Allocator) !void {
    if (intrinsics_loaded) return;

    const intrinsics_dir = "artifacts/cuda_intrinsics";

    var dir = std.fs.cwd().openDir(intrinsics_dir, .{ .iterate = true }) catch |err| {
        log.err("failed to open {s}: {s}", .{ intrinsics_dir, @errorName(err) });
        log.err("Run: python3 scripts/generate_cuda_intrinsics.py", .{});
        return err;
    };
    defer dir.close();

    log.info("Loading CUDA intrinsics from {s}/", .{intrinsics_dir});

    var loaded_count: usize = 0;
    var iter = dir.iterate();
    while (try iter.next()) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".json")) continue;

        const json_data = dir.readFileAlloc(allocator, entry.name, 1_000_000) catch |err| {
            log.warn("failed to read {s}: {s}", .{ entry.name, @errorName(err) });
            continue;
        };
        defer allocator.free(json_data);

        // extract name, desc, impl
        const parsed = std.json.parseFromSlice(
            struct {
                name: []const u8,
                desc: []const u8,
                impl: []const u8,
            },
            allocator,
            json_data,
            .{},
        ) catch |err| {
            log.warn("failed to parse {s}: {s}", .{ entry.name, @errorName(err) });
            continue;
        };
        defer parsed.deinit();

        const intrinsic_data = parsed.value;

        // convert to C strings
        const name_cstr = try api.cstr_alloc(allocator, intrinsic_data.name);
        defer allocator.free(name_cstr);

        const desc_cstr = try api.cstr_alloc(allocator, intrinsic_data.desc);
        defer allocator.free(desc_cstr);

        const impl_cstr = try api.cstr_alloc(allocator, intrinsic_data.impl);
        defer allocator.free(impl_cstr);

        // load PrimFuncs from json
        const desc_primfunc = try api.call_global(allocator, "node.LoadJSON", &.{Value.str(desc_cstr.ptr)});

        const impl_primfunc = try api.call_global(allocator, "node.LoadJSON", &.{Value.str(impl_cstr.ptr)});

        // create TensorIntrin object
        const tensor_intrin = try api.call_global(allocator, "tir.TensorIntrin", &.{ desc_primfunc, impl_primfunc });

        // register intrinsic
        _ = try api.call_global(allocator, "tir.TensorIntrinRegister", &.{
            Value.str(name_cstr.ptr),
            tensor_intrin,
            Value.boolean(false), // override=false
        });

        loaded_count += 1;
    }

    log.info("Loaded {d} CUDA tensor intrinsics", .{loaded_count});
    intrinsics_loaded = true;
}

/// Filter kind for separating host and device functions.
pub const FilterKind = enum {
    host,
    device,
};

/// Filter module to keep only functions matching the target kind.
///
/// Uses TVM's tir.transform.Filter pass directly via FFI with a Zig callback.
///
/// ## Notes
/// - Avoids fork() which corrupts the heap in multi-threaded TVM processes.
/// - Host functions have calling_conv = kCPackedFunc (1)
/// - Device functions have calling_conv = kDefault (0) or kDeviceKernelLaunch (2)
pub fn filter_module_by_target(
    allocator: std.mem.Allocator,
    module: c.TVMFFIAny,
    kind: FilterKind,
) !c.TVMFFIAny {
    const want_host: bool = (kind == .host);

    // create a tvm function that wraps our filter predicate
    var filter_func: c.TVMFFIObjectHandle = std.mem.zeroes(c.TVMFFIObjectHandle);

    const callback_fn: *const fn (?*anyopaque, [*c]const c.TVMFFIAny, i32, [*c]c.TVMFFIAny) callconv(.c) c_int =
        if (want_host) &filter_host_callback else &filter_device_callback;

    const ret = c.TVMFFIFunctionCreate(
        null,
        @ptrCast(callback_fn),
        null,
        &filter_func,
    );
    if (ret != 0) {
        log.err("Failed to create filter callback function", .{});
        return error.TvmFfiError;
    }
    defer _ = c.TVMFFIObjectDecRef(filter_func);

    // wrap the function handle as a TVMFFIAny
    var filter_func_any = std.mem.zeroes(c.TVMFFIAny);
    filter_func_any.type_index = c.kTVMFFIFunction;
    filter_func_any.unnamed_1.v_obj = @alignCast(@ptrCast(filter_func));
    // IncRef bc we still hold the handle via defer
    _ = c.TVMFFIObjectIncRef(filter_func);

    // use tir.transform.Filter(callback) to create a pass
    const filter_pass = try api.call_global(allocator, "tir.transform.Filter", &.{Value{ .raw = filter_func_any }});
    defer filter_pass.decref();

    // apply pass: filtered_mod = filter_pass(module)
    const filtered_result = try api.call_global(allocator, "transform.RunPass", &.{ filter_pass, Value{ .raw = module } });
    const filtered_mod = filtered_result.raw;

    log.debug("Filtered module for {s} (inline FFI), type_index={d}", .{ @tagName(kind), filtered_mod.type_index });
    return filtered_mod;
}

/// Filter callback: keep host functions (calling_conv == 1).
fn filter_host_callback(
    handle: ?*anyopaque,
    args: [*c]const c.TVMFFIAny,
    num_args: i32,
    ret: [*c]c.TVMFFIAny,
) callconv(.c) c_int {
    return filter_by_calling_conv(handle, args, num_args, ret, true);
}

/// Filter callback: keep device functions (calling_conv != 1).
fn filter_device_callback(
    handle: ?*anyopaque,
    args: [*c]const c.TVMFFIAny,
    num_args: i32,
    ret: [*c]c.TVMFFIAny,
) callconv(.c) c_int {
    return filter_by_calling_conv(handle, args, num_args, ret, false);
}

/// Shared filter logic: check calling_conv attribute of a PrimFunc.
///
/// Accesses calling_conv via TVM FFI registered functions:
/// 1. `ir.BaseFunc_Attrs(func)` -> DictAttrs
/// 2. `ir.DictAttrsGetDict(dict_attrs)` -> Map<String, Any>
/// 3. `ffi.MapCount(map, "calling_conv")` -> existence check
/// 4. `ffi.MapGetItem(map, "calling_conv")` -> IntImm value
/// 5. Extract int via reflection field getter (IntImm stores value as object)
fn filter_by_calling_conv(
    handle: ?*anyopaque,
    args: [*c]const c.TVMFFIAny,
    num_args: i32,
    ret: [*c]c.TVMFFIAny,
    want_host: bool,
) c_int {
    _ = handle;

    if (num_args != 1) {
        log.err("filter callback: expected 1 arg, got {d}", .{num_args});
        return -1;
    }

    const func_any = args[0];

    // for tmp allocations where lifetime is scoped to this callback
    var arena = std.heap.ArenaAllocator.init(std.heap.c_allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    const default_ret = Value.boolean(!want_host).raw;
    var calling_conv: i64 = 0; // default = kDefault (device)

    // 1. Get attrs from the PrimFunc
    const dict_attrs = api.call_global(alloc, "ir.BaseFunc_Attrs", &.{Value{ .raw = func_any }}) catch {
        ret.* = default_ret;
        return 0;
    };
    defer dict_attrs.decref();

    // if attrs is None then no attributes set
    if (dict_attrs.is_none()) {
        ret.* = default_ret;
        return 0;
    }

    // 2. Get the underlying Map from DictAttrs
    const map = api.call_global(alloc, "ir.DictAttrsGetDict", &.{dict_attrs}) catch {
        ret.* = default_ret;
        return 0;
    };
    defer map.decref();

    // 3. Create a TVM String key for "calling_conv"
    // NB: must be a proper tvm string (not raw c str) so Map key comparison works
    const key = api.make_tvm_string("calling_conv") catch {
        ret.* = default_ret;
        return 0;
    };
    defer key.decref();

    // 4. Check if "calling_conv" exists in the Map
    const count = api.call_global(alloc, "ffi.MapCount", &.{ map, key }) catch {
        ret.* = default_ret;
        return 0;
    };

    if ((count.as_int() orelse 0) == 0) {
        ret.* = default_ret;
        return 0;
    }

    // 5. Get the calling_conv value from the Map
    const conv_val = api.call_global(alloc, "ffi.MapGetItem", &.{ map, key }) catch {
        ret.* = default_ret;
        return 0;
    };
    defer conv_val.decref();

    // 6. Extract integer value
    // NB: needs to handle both raw int and IntImm objects
    if (get_int_from_any(conv_val.raw)) |val| {
        calling_conv = val;
    }

    // kDefault=0 (device), kCPackedFunc=1 (host), kDeviceKernelLaunch=2 (device)
    const is_host = (calling_conv == 1);
    log.debug("filter: calling_conv={d}, is_host={}, want_host={}", .{ calling_conv, is_host, want_host });
    ret.* = Value.boolean(is_host == want_host).raw;
    return 0;
}

/// Extract an integer value from a TVMFFIAny.
///
/// Handles both raw kTVMFFIInt values and IntImm TVM objects.
/// For IntImm, uses TVM's reflection system (TVMFFIGetTypeInfo) to access
/// the "value" field via the registered field getter.
fn get_int_from_any(any: c.TVMFFIAny) ?i64 {
    // fast path: already a raw int
    if (any.type_index == c.kTVMFFIInt) return any.unnamed_1.v_int64;

    // object path: use reflection to find "value" field (works for IntImm)
    if (any.type_index >= c.kTVMFFIStaticObjectBegin) {
        const obj_ptr = any.unnamed_1.v_obj orelse return null;
        const type_info = c.TVMFFIGetTypeInfo(any.type_index);
        if (type_info == null) return null;

        const num_fields: usize = @intCast(type_info[0].num_fields);
        if (type_info[0].fields == null) return null;

        for (0..num_fields) |i| {
            const field = type_info[0].fields[i];
            const name_slice = field.name.data[0..field.name.size];
            if (std.mem.eql(u8, name_slice, "value")) {
                const getter_fn = field.getter orelse return null;
                const addr: usize = @intFromPtr(obj_ptr) + @as(usize, @intCast(field.offset));
                const field_addr: *anyopaque = @ptrFromInt(addr);
                var result: c.TVMFFIAny = std.mem.zeroes(c.TVMFFIAny);
                if (getter_fn(field_addr, &result) == 0 and result.type_index == c.kTVMFFIInt) {
                    return result.unnamed_1.v_int64;
                }
                return null;
            }
        }
    }
    return null;
}

/// Build CUDA device kernels.
///
/// Takes a module containing only device functions (after filtering)
/// and compiles them with target.build.cuda.
pub fn build_device_kernels(
    allocator: std.mem.Allocator,
    device_mod: c.TVMFFIAny,
    target: c.TVMFFIAny,
) !c.TVMFFIAny {
    log.debug("build_device_kernels: entering (device_mod type_index={d})", .{device_mod.type_index});
    log.debug("build_device_kernels: calling target.build.cuda", .{});
    const result = try api.call_global(allocator, "target.build.cuda", &.{
        Value{ .raw = device_mod },
        Value{ .raw = target },
    });
    log.debug("build_device_kernels: success (built_mod type_index={d})", .{result.raw.type_index});
    return result.raw;
}

/// Build LLVM host wrapper for device kernels.
///
/// Takes a module containing only host functions (after filtering)
/// and compiles them with target.build.llvm.
pub fn build_host_wrapper(
    allocator: std.mem.Allocator,
    host_mod: c.TVMFFIAny,
    target: c.TVMFFIAny,
) !c.TVMFFIAny {
    const result = try api.call_global(allocator, "target.build.llvm", &.{
        Value{ .raw = host_mod },
        Value{ .raw = target },
    });
    return result.raw;
}

/// Link device module into host module.
///
/// After building host and device modules separately, this imports
/// the device module into the host module so the host can call
/// device kernels.
pub fn link_device_module(
    allocator: std.mem.Allocator,
    host_built: c.TVMFFIAny,
    device_built: c.TVMFFIAny,
) !void {
    _ = try api.call_global(allocator, "ffi.ModuleImportModule", &.{
        Value{ .raw = host_built },
        Value{ .raw = device_built },
    });
    log.debug("Linked device module into host module", .{});
}
