<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'

let script_element: HTMLScriptElement | null = null
let hash_change_handler: (() => void) | null = null
let original_fetch: typeof window.fetch | null = null

function set_status(message: string): void {
  const status = document.getElementById('status')

  if (status) {
    status.textContent = message
  }
}

function rewrite_autodoc_request(input: RequestInfo | URL): RequestInfo | URL {
  if (typeof input === 'string') {
    if (input === 'main.wasm' || input === 'sources.tar') {
      return `/autodoc/${input}`
    }
  }

  if (input instanceof URL) {
    if (input.pathname === '/main.wasm' || input.pathname === '/sources.tar') {
      return new URL(`/api${input.pathname}`, input.origin)
    }
  }

  if (typeof Request !== 'undefined' && input instanceof Request) {
    const url = new URL(input.url)

    if (url.pathname === '/main.wasm' || url.pathname === '/sources.tar') {
      return new Request(`/api${url.pathname}`, input)
    }
  }

  return input
}

onMounted(() => {
  original_fetch = window.fetch.bind(window)
  window.fetch = ((input: RequestInfo | URL, init?: RequestInit) => {
    return original_fetch!(rewrite_autodoc_request(input), init)
  }) as typeof window.fetch

  script_element = document.createElement('script')
  script_element.src = '/autodoc/main.js'
  script_element.async = true

  script_element.onload = () => {
    hash_change_handler = () => {
      window.dispatchEvent(new PopStateEvent('popstate', { state: null }))
    }

    window.addEventListener('hashchange', hash_change_handler)
  }

  script_element.onerror = () => {
    set_status('Failed to load documentation. Please refresh the page.')
  }

  document.body.appendChild(script_element)
})

onUnmounted(() => {
  if (hash_change_handler) {
    window.removeEventListener('hashchange', hash_change_handler)
    hash_change_handler = null
  }

  if (original_fetch) {
    window.fetch = original_fetch
    original_fetch = null
  }

  if (script_element && document.body.contains(script_element)) {
    document.body.removeChild(script_element)
    script_element = null
  }
})
</script>

<template>
  <UContainer>
  <UPage>
    <UPageHeader
      title="API Reference"
      description="Autogenerated Zigrad API reference"
    />

    <UPageBody>
      <div class="zig-autodoc">
        <div id="navWrap">
          <input
            id="search"
            type="search"
            class="search-input"
            placeholder="`s` to search, `?` to see more options"
            autocomplete="off"
            spellcheck="false"
          >

          <div
            id="sectNav"
            class="hidden"
          >
            <ul id="listNav" />
          </div>
        </div>

        <section class="zig-autodoc__content">
          <p id="status">
            Loading...
          </p>

          <h1
            id="hdrName"
            class="hidden"
          >
            <span />
            <a href="#">[src]</a>
          </h1>

          <div
            id="fnProto"
            class="hidden"
          >
            <pre><code id="fnProtoCode" /></pre>
          </div>

          <div
            id="tldDocs"
            class="hidden"
          />

          <div
            id="sectParams"
            class="hidden"
          >
            <h2>Parameters</h2>
            <div id="listParams" />
          </div>

          <div
            id="sectFnErrors"
            class="hidden"
          >
            <h2>Errors</h2>

            <div id="fnErrorsAnyError">
              <p>
                <span class="tok-type">anyerror</span> means the error set is known only at runtime.
              </p>
            </div>

            <div id="tableFnErrors">
              <dl id="listFnErrors" />
            </div>
          </div>

          <div
            id="sectSearchResults"
            class="hidden"
          >
            <h2>Search Results</h2>
            <ul id="listSearchResults" />
          </div>

          <div
            id="sectSearchNoResults"
            class="hidden"
          >
            <h2>No Results Found</h2>
            <p>Press escape to exit search and then `?` to see more options.</p>
          </div>

          <div
            id="sectFields"
            class="hidden"
          >
            <h2>Fields</h2>
            <div id="listFields" />
          </div>

          <div
            id="sectTypes"
            class="hidden"
          >
            <h2>Types</h2>
            <ul
              id="listTypes"
              class="columns"
            />
          </div>

          <div
            id="sectNamespaces"
            class="hidden"
          >
            <h2>Namespaces</h2>
            <ul
              id="listNamespaces"
              class="columns"
            />
          </div>

          <div
            id="sectGlobalVars"
            class="hidden"
          >
            <h2>Global Variables</h2>
            <table>
              <tbody id="listGlobalVars" />
            </table>
          </div>

          <div
            id="sectValues"
            class="hidden"
          >
            <h2>Values</h2>
            <table>
              <tbody id="listValues" />
            </table>
          </div>

          <div
            id="sectFns"
            class="hidden"
          >
            <h2>Functions</h2>
            <dl id="listFns" />
          </div>

          <div
            id="sectErrSets"
            class="hidden"
          >
            <h2>Error Sets</h2>
            <ul
              id="listErrSets"
              class="columns"
            />
          </div>

          <div
            id="sectDocTests"
            class="hidden"
          >
            <h2>Example Usage</h2>
            <pre><code id="docTestsCode" /></pre>
          </div>

          <div
            id="sectSource"
            class="hidden"
          >
            <h2>Source Code</h2>
            <pre><code id="sourceText" /></pre>
          </div>
        </section>

        <div
          id="helpDialog"
          class="hidden"
        >
          <h2>Keyboard Shortcuts</h2>
          <dl><dt><kbd>?</kbd></dt><dd>Show this help dialog</dd></dl>
          <dl><dt><kbd>Esc</kbd></dt><dd>Clear focus; close this dialog</dd></dl>
          <dl><dt><kbd>s</kbd></dt><dd>Focus the search field</dd></dl>
          <dl><dt><kbd>u</kbd></dt><dd>Go to source code</dd></dl>
          <dl><dt><kbd>↑</kbd></dt><dd>Move up in search results</dd></dl>
          <dl><dt><kbd>↓</kbd></dt><dd>Move down in search results</dd></dl>
          <dl><dt><kbd>⏎</kbd></dt><dd>Go to active search result</dd></dl>
        </div>

        <div
          id="errors"
          class="hidden"
        >
          <h2>Errors</h2>
          <pre id="errorsText" />
        </div>
      </div>
    </UPageBody>
  </UPage>
  </UContainer>
</template>

<style>
.zig-autodoc {
  color: var(--ui-text-toned);
}

.zig-autodoc *,
.zig-autodoc *::before,
.zig-autodoc *::after {
  box-sizing: border-box;
}

.zig-autodoc .hidden {
  display: none;
}

.zig-autodoc a {
  color: var(--ui-primary);
  text-decoration: none;
}

.zig-autodoc a:hover {
  text-decoration: underline;
}

.zig-autodoc pre,
.zig-autodoc code,
.zig-autodoc input,
.zig-autodoc kbd {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
}

.zig-autodoc pre {
  margin: 0;
  overflow-x: auto;
  border: 1px solid var(--ui-border-muted);
  border-radius: 0.75rem;
  background: var(--ui-bg-muted);
  padding: 1rem;
  color: var(--ui-text-highlighted);
}

.zig-autodoc :not(pre) > code {
  white-space: break-spaces;
}

.zig-autodoc table {
  width: 100%;
  border-collapse: collapse;
}

.zig-autodoc td,
.zig-autodoc th {
  vertical-align: top;
  padding: 0.75rem;
  text-align: left;
}

.zig-autodoc td {
  border-top: 1px solid var(--ui-border-muted);
}

.zig-autodoc .columns {
  column-width: 20rem;
}

.zig-autodoc #navWrap {
  margin-bottom: 1rem;
}

.zig-autodoc #search {
  width: 100%;
  border: 1px solid var(--ui-border);
  border-radius: 0.75rem;
  background: var(--ui-bg);
  padding: 0.875rem 1rem;
  color: var(--ui-text-highlighted);
}

.zig-autodoc #search::placeholder {
  color: var(--ui-text-dimmed);
}

.zig-autodoc #listNav {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  list-style: none;
  margin: 0.75rem 0 0;
  padding: 0;
}

.zig-autodoc #listNav li {
  margin: 0;
}

.zig-autodoc #listNav li a {
  display: block;
  border: 1px solid var(--ui-border);
  border-radius: 9999px;
  background: var(--ui-bg-muted);
  padding: 0.45rem 0.8rem;
  color: var(--ui-text-toned);
}

.zig-autodoc #listNav li a:hover,
.zig-autodoc #listNav li a.active {
  background: var(--ui-primary);
  border-color: var(--ui-primary);
  color: var(--ui-bg);
  text-decoration: none;
}

.zig-autodoc .zig-autodoc__content > * + * {
  margin-top: 1.5rem;
}

.zig-autodoc section h1,
.zig-autodoc section h2 {
  color: var(--ui-text-highlighted);
}

.zig-autodoc section h1 {
  margin: 0;
  border-bottom: 1px solid var(--ui-border);
  padding-bottom: 0.75rem;
  font-size: 1.875rem;
  font-weight: 700;
}

.zig-autodoc section h2 {
  margin: 0 0 0.75rem;
  border-bottom: 1px solid var(--ui-border-muted);
  padding-bottom: 0.5rem;
  font-size: 1.125rem;
  font-weight: 600;
}

.zig-autodoc #hdrName a {
  padding-left: 0.75rem;
  font-size: 0.75em;
}

.zig-autodoc #listFields > div,
.zig-autodoc #listParams > div,
.zig-autodoc dl > div {
  margin-top: 0.75rem;
  border: 1px solid var(--ui-border-muted);
  border-radius: 0.75rem;
  background: var(--ui-bg-muted);
  padding: 0.9rem 1rem;
}

.zig-autodoc .fieldDocs {
  margin-top: -1px;
  border: 1px solid var(--ui-border-muted);
  border-top: 0;
  border-radius: 0 0 0.75rem 0.75rem;
  background: var(--ui-bg-elevated);
  padding: 0.85rem 1rem;
}

.zig-autodoc #tableFnErrors dt {
  font-weight: 700;
}

.zig-autodoc #listSearchResults li.selected {
  border-radius: 0.5rem;
  background: color-mix(in srgb, var(--ui-primary) 18%, transparent);
}

.zig-autodoc #helpDialog {
  position: fixed;
  top: 1rem;
  left: 1rem;
  z-index: 50;
  width: min(24rem, calc(100vw - 2rem));
  border: 1px solid var(--ui-border);
  border-radius: 1rem;
  background: var(--ui-bg-elevated);
  padding: 1rem 1.25rem;
  color: var(--ui-text-highlighted);
  box-shadow: 0 20px 50px rgb(0 0 0 / 0.35);
}

.zig-autodoc #helpDialog dl {
  margin: 0.5rem 0 0;
}

.zig-autodoc #helpDialog dt,
.zig-autodoc #helpDialog dd {
  display: inline;
  margin: 0 0.2em;
}

.zig-autodoc kbd {
  display: inline-block;
  border: 1px solid var(--ui-border);
  border-bottom-color: var(--ui-border-accented);
  border-radius: 0.4rem;
  background: var(--ui-bg);
  padding: 0.2rem 0.35rem;
  font-size: 0.95em;
  line-height: 1;
  color: var(--ui-text-highlighted);
}

.zig-autodoc #errors {
  position: fixed;
  right: 1rem;
  bottom: 1rem;
  z-index: 50;
  width: min(42rem, calc(100vw - 2rem));
  max-height: min(24rem, 60vh);
  overflow: auto;
  border: 1px solid color-mix(in srgb, var(--ui-error) 45%, var(--ui-border));
  border-radius: 1rem;
  background: color-mix(in srgb, var(--ui-error) 10%, var(--ui-bg-elevated));
  padding: 1rem 1.25rem;
}

.zig-autodoc #errors pre {
  border-color: color-mix(in srgb, var(--ui-error) 35%, var(--ui-border));
  background: color-mix(in srgb, var(--ui-error) 6%, var(--ui-bg-muted));
}

.zig-autodoc .tok-kw {
  color: var(--autodoc-token-keyword);
  font-weight: 700;
}

.zig-autodoc .tok-str {
  color: var(--autodoc-token-string);
}

.zig-autodoc .tok-builtin {
  color: var(--autodoc-token-builtin);
}

.zig-autodoc .tok-comment {
  color: var(--autodoc-token-comment);
  font-style: italic;
}

.zig-autodoc .tok-fn {
  color: var(--autodoc-token-function);
  font-weight: 700;
}

.zig-autodoc .tok-null,
.zig-autodoc .tok-number {
  color: var(--autodoc-token-number);
}

.zig-autodoc .tok-type {
  color: var(--autodoc-token-type);
  font-weight: 700;
}

@media (max-width: 768px) {
  .zig-autodoc td,
  .zig-autodoc th {
    display: block;
    width: 100%;
  }
}
</style>
