<template>
  <UPage>
    <UPageHeader
      title="API Reference"
      description="Autogenerated Zigrad API Reference"
    />

    <UPageBody>
      <iframe
        src="/api/index.html"
        title="Zig autodoc"
        style="display:block;width:100%;min-height:84vh;border:1px solid var(--ui-border);border-radius:.5rem;background:var(--ui-bg);"
      ></iframe>
    </UPageBody>
  </UPage>
</template>
