# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "cova-0.10.1-_OE4R_fhBABRyLixvgKSbSh6G3JUVSA3MYqYwUGVuaxH";
    path = fetchgit {
      url = "https://github.com/Marco-Christiani/cova";
      rev = "dd159f1ce6d1ee45a39e2999b0944894ed02ec2a";
      hash = "sha256-MWY17+cZXJ6kD953tgLVEAEHFdu5NPX7L5sWJPhNwFc=";
    };
  }
  {
    name = "safetensors_zg-0.0.1-dRXUiGDtAAAS8GBHZT5IfFha7hG6KXCtVUuUxB-ob4Jc";
    path = fetchgit {
      url = "https://github.com/Marco-Christiani/safetensors-zg";
      rev = "15787b35b541a4493630ec383750242eef422b64";
      hash = "sha256-AEf0Eero0NuUbH/R79ALXBtkbj8zWl859qV7RFNOQO0=";
    };
  }
]
