# Repository development tools that are not Zigrad build configurations.
{
  perSystem = {
    pkgs,
    config,
    cudaCfg,
    ...
  }: let
    externalSources = import ../external-sources.nix {inherit pkgs;};
    cudaToolkit = config.packages.cuda-redist-dev;
    genClangd = pkgs.writeShellScriptBin "gen-clangd" ''
      set -euo pipefail

      root="$(${pkgs.lib.getExe pkgs.git} rev-parse --show-toplevel)"
      printf 'Generating .clangd root=%s\n' "$root"

      tmp="$(mktemp)"
      cat > "$tmp" <<EOF
      CompileFlags:
        CompilationDatabase: build
        Add:
          - -I${cudaToolkit}/include
          - -xcuda
          - --cuda-path=${cudaToolkit}
          - --no-cuda-version-check
        Remove:
          - -forward-unknown-to-host-compiler

      Diagnostics:
        UnusedIncludes: None
        MissingIncludes: None
      EOF

      mv "$tmp" "$root/.clangd"
      printf 'Wrote %s/.clangd\n' "$root"
    '';

    genNvim = pkgs.writeShellScriptBin "gen-nvim" ''
      set -euo pipefail

      root="$(${pkgs.lib.getExe pkgs.git} rev-parse --show-toplevel)"
      tmp="$(mktemp)"
      cat > "$tmp" <<EOF
      -- generated by nix/flake/tools.nix. do not edit.

      vim.lsp.config["zls"] = {
        cmd = { "${pkgs.zls}/bin/zls" },
        root_marker = { "build.zig", ".git" },
        filetypes = { "zig" },
      }

      vim.lsp.enable("zls")
      EOF

      mv "$tmp" "$root/.nvim.local.lua"
      printf 'Wrote %s/.nvim.local.lua\n' "$root"
    '';

    checkSdkPython = pkgs.python3.withPackages (pythonPackages: [
      pythonPackages.pyelftools
    ]);

    checkSdk = pkgs.writeShellApplication {
      name = "check-sdk";
      runtimeInputs = [checkSdkPython];
      text = ''
        exec python3 ${../../scripts/check_sdk.py} "$@"
      '';
    };

    updateCudaCatalog = pkgs.writeShellApplication {
      name = "update-cuda-catalog";
      runtimeInputs = [pkgs.python3];
      text = ''
        export PYTHONPATH=${../../scripts}
        exec python3 ${../../scripts/update_cuda_catalog.py} \
          --xla-src ${externalSources.xla.src} \
          --cuda-version ${cudaCfg.cudaVersion} \
          --cudnn-version ${cudaCfg.cudnnVersion} \
          --nvshmem-version ${cudaCfg.nvshmemVersion} \
          --nccl-version ${cudaCfg.ncclVersion} \
          "$@"
      '';
    };

    checkDependencySnapshot = pkgs.writeShellApplication {
      name = "check-dependency-snapshot";
      runtimeInputs = [pkgs.python3];
      text = ''
        export PYTHONPATH=${../../scripts}
        exec python3 ${../../scripts/check_dependency_snapshot.py} \
          --repo "$PWD" \
          --xla-src ${externalSources.xla.src} \
          --llvm-src ${externalSources.llvm.src} \
          "$@"
      '';
    };

    planDependencies = pkgs.writeShellApplication {
      name = "plan-dependencies";
      runtimeInputs = [
        pkgs.git
        pkgs.nix
        pkgs.nix-prefetch-git
        pkgs.python3
      ];
      text = ''
        export PYTHONPATH=${../../scripts}
        exec python3 ${../../scripts/plan_dependencies.py} \
          --manifest ${config.packages.zigrad-build-configurations} \
          --snapshot ${../external-sources.json} \
          --xla-src ${externalSources.xla.src} \
          --llvm-src ${externalSources.llvm.src} \
          --tvm-src ${externalSources.tvm.src} \
          --iree-llvm-src ${externalSources.iree_llvm.src} \
          "$@"
      '';
    };

    dependencyPlannerTests =
      pkgs.runCommand "dependency-planner-tests" {
        nativeBuildInputs = [pkgs.python3];
      } ''
        export PYTHONPATH=${../../scripts}
        python3 ${../../scripts/test_dependency_planner.py}
        touch "$out"
      '';
  in {
    packages = {
      check-dependency-snapshot = checkDependencySnapshot;
      check-sdk = checkSdk;
      gen-clangd = genClangd;
      gen-nvim = genNvim;
      plan-dependencies = planDependencies;
      update-cuda-catalog = updateCudaCatalog;
    };

    apps = {
      check-dependency-snapshot = {
        type = "app";
        program = "${checkDependencySnapshot}/bin/check-dependency-snapshot";
        meta.description = "Validate the external dependency snapshot";
      };
      plan-dependencies = {
        type = "app";
        program = "${planDependencies}/bin/plan-dependencies";
        meta.description = "Explain dependency compatibility for a build configuration";
      };
      gen-clangd = {
        type = "app";
        program = "${genClangd}/bin/gen-clangd";
        meta.description = "Generate the repository clangd configuration";
      };
      gen-nvim = {
        type = "app";
        program = "${genNvim}/bin/gen-nvim";
        meta.description = "Generate the repository Neovim configuration";
      };
      ccache = {
        type = "app";
        program = "${pkgs.ccache}/bin/ccache";
        meta.description = "Run ccache from the pinned development toolchain";
      };
      check-sdk = {
        type = "app";
        program = "${checkSdk}/bin/check-sdk";
        meta.description = "Inspect external input ELF dependencies";
      };
      update-cuda-catalog = {
        type = "app";
        program = "${updateCudaCatalog}/bin/update-cuda-catalog";
        meta.description = "Update exact CUDA redistributable catalog entries";
      };
    };

    checks.dependency-planner = dependencyPlannerTests;
  };
}
