# Repository development tools that are not Zigrad build configurations.
{
  perSystem = {
    pkgs,
    config,
    cudaCfg,
    repoRoot,
    ...
  }: let
    buildConfigurations = config.zigrad.resolvedConfigurations;
    externalSources = import ../external-sources.nix {inherit pkgs;};
    cudaToolkit = config.packages.cuda-redist-dev;
    genClangd = pkgs.writeShellScriptBin "gen-clangd" ''
      set -euo pipefail

      root="$(${pkgs.lib.getExe pkgs.git} rev-parse --show-toplevel)"
      printf 'Generating .clangd root=%s\n' "$root"

      tmp="$(mktemp)"
      cat > "$tmp" <<EOF
      CompileFlags:
        CompilationDatabase: build
        Add:
          - -I${cudaToolkit}/include
          - -xcuda
          - --cuda-path=${cudaToolkit}
          - --no-cuda-version-check
        Remove:
          - -forward-unknown-to-host-compiler

      Diagnostics:
        UnusedIncludes: None
        MissingIncludes: None
      EOF

      mv "$tmp" "$root/.clangd"
      printf 'Wrote %s/.clangd\n' "$root"
    '';

    genNvim = pkgs.writeShellScriptBin "gen-nvim" ''
      set -euo pipefail

      root="$(${pkgs.lib.getExe pkgs.git} rev-parse --show-toplevel)"
      tmp="$(mktemp)"
      cat > "$tmp" <<EOF
      -- generated by nix/flake/tools.nix. do not edit.

      vim.lsp.config["zls"] = {
        cmd = { "${pkgs.zls}/bin/zls" },
        root_marker = { "build.zig", ".git" },
        filetypes = { "zig" },
      }

      vim.lsp.enable("zls")
      EOF

      mv "$tmp" "$root/.nvim.local.lua"
      printf 'Wrote %s/.nvim.local.lua\n' "$root"
    '';

    checkSdkPython = pkgs.python3.withPackages (pythonPackages: [
      pythonPackages.pyelftools
    ]);

    checkSdk = pkgs.writeShellApplication {
      name = "check-sdk";
      runtimeInputs = [checkSdkPython];
      text = ''
        exec python3 ${repoRoot + /scripts/check_sdk.py} "$@"
      '';
    };

    updateCudaCatalog = pkgs.writeShellApplication {
      name = "update-cuda-catalog";
      runtimeInputs = [pkgs.python3];
      text = ''
        export PYTHONPATH=${repoRoot + /scripts}
        exec python3 ${repoRoot + /scripts/update_cuda_catalog.py} \
          --xla-src ${externalSources.xla.src} \
          --cuda-version ${cudaCfg.cudaVersion} \
          --cudnn-version ${cudaCfg.cudnnVersion} \
          --nvshmem-version ${cudaCfg.nvshmemVersion} \
          --nccl-version ${cudaCfg.ncclVersion} \
          "$@"
      '';
    };

    checkDependencySnapshot = pkgs.writeShellApplication {
      name = "check-dependency-snapshot";
      runtimeInputs = [pkgs.python3];
      text = ''
        export PYTHONPATH=${repoRoot + /scripts}
        exec python3 ${repoRoot + /scripts/check_dependency_snapshot.py} \
          --repo "$PWD" \
          --xla-src ${externalSources.xla.src} \
          --llvm-src ${externalSources.llvm.src} \
          "$@"
      '';
    };

    planDependencies = pkgs.writeShellApplication {
      name = "plan-dependencies";
      runtimeInputs = [
        pkgs.git
        pkgs.nix
        pkgs.nix-prefetch-git
        pkgs.python3
      ];
      text = ''
        export PYTHONPATH=${repoRoot + /scripts}
        exec python3 ${repoRoot + /scripts/plan_dependencies.py} \
          --manifest ${config.packages.zigrad-build-configurations} \
          --snapshot ${repoRoot + /nix/external-sources.json} \
          --xla-src ${externalSources.xla.src} \
          --llvm-src ${externalSources.llvm.src} \
          --tvm-src ${externalSources.tvm.src} \
          --iree-llvm-src ${externalSources.iree_llvm.src} \
          "$@"
      '';
    };

    dependencyPlannerTests =
      pkgs.runCommand "dependency-planner-tests" {
        nativeBuildInputs = [pkgs.python3];
      } ''
        export PYTHONPATH=${repoRoot + /scripts}
        python3 ${repoRoot + /scripts/test_dependency_planner.py}
        touch "$out"
      '';

    buildConfigurationManifest = config.packages.zigrad-build-configurations;
    buildConfigurationNames = builtins.attrNames buildConfigurations;
    pog = pkgs.pog.pog;
    zigradBuild = pog {
      name = "zigrad-build";
      description = "Inspect Zigrad build configurations";
      runtimeInputs = [
        pkgs.jq
        pkgs.util-linux
      ];
      strict = true;
      commands = [
        {
          name = "config";
          description = "Inspect named build configurations";
          commands = [
            {
              name = "list";
              description = "List build configurations";
              flags = [
                {
                  name = "all";
                  short = "a";
                  bool = true;
                  description = "include internal configurations";
                }
              ];
              script = helpers:
                with helpers; ''
                  include_all=false
                  if ${flag "all"}; then
                    include_all=true
                  fi

                  jq --raw-output --argjson include_all "$include_all" '
                    def render:
                      map(.provider + ":" + .target)
                      | if length == 0 then "-" else join(",") end;

                    ["CONFIG", "COMPILERS", "KERNEL PROVIDERS", "RUNTIMES"],
                    (
                      to_entries
                      | map(select($include_all or .value.expose))
                      | sort_by(.key)[]
                      | [
                          .key,
                          (.value.compilers | render),
                          (.value.kernelProviders | render),
                          (.value.runtimes | render)
                        ]
                    )
                    | @tsv
                  ' ${buildConfigurationManifest} | column --table --separator $'\t'
                '';
            }
            {
              name = "show";
              description = "Show one build configuration";
              arguments = [
                {
                  name = "name";
                  description = "configuration name";
                  completion = pog.completions.values buildConfigurationNames;
                }
              ];
              script = helpers:
                with helpers; ''
                  name="''${1:-}"
                  [[ -n "$name" ]] || die "configuration name required" 2
                  jq --exit-status --raw-output --arg name "$name" '
                    def render($values):
                      $values
                      | map(.provider + ":" + .target)
                      | if length == 0 then "-" else join(", ") end;
                    def lines($values):
                      if ($values | length) == 0 then "  -"
                      else $values | map("  " + .) | join("\n")
                      end;
                    def inline($values):
                      if ($values | length) == 0 then "-"
                      else $values | join(", ")
                      end;

                    if has($name) then
                      .[$name] as $config
                      | [
                          "name: " + $name,
                          "description: " + $config.description,
                          "exposed: " + ($config.expose | tostring),
                          "compilers: " + render($config.compilers),
                          "kernel providers: " + render($config.kernelProviders),
                          "runtimes: " + render($config.runtimes),
                          "demands:\n" + lines($config.demands),
                          "resolved nodes:\n" + lines($config.resolved),
                          "Zig dependency sets:\n" + lines($config.zigDependencySets),
                          "Zig feature flags:\n" + lines($config.zigFeatureArgs),
                          "runtime environment:",
                          "  fixed: " + inline($config.runtimeEnvironment.fixed),
                          "  defaulted: " + inline($config.runtimeEnvironment.defaults),
                          "  prefixed: " + inline($config.runtimeEnvironment.prefixes)
                        ]
                      | join("\n")
                    else
                      error("unknown build configuration: " + $name)
                    end
                  ' ${buildConfigurationManifest}
                '';
            }
          ];
        }
      ];
    };
  in {
    packages = {
      check-dependency-snapshot = checkDependencySnapshot;
      check-sdk = checkSdk;
      gen-clangd = genClangd;
      gen-nvim = genNvim;
      plan-dependencies = planDependencies;
      update-cuda-catalog = updateCudaCatalog;
      zigrad-build = zigradBuild;
    };

    apps = {
      check-dependency-snapshot = {
        type = "app";
        program = "${checkDependencySnapshot}/bin/check-dependency-snapshot";
        meta.description = "Validate the external dependency snapshot";
      };
      plan-dependencies = {
        type = "app";
        program = "${planDependencies}/bin/plan-dependencies";
        meta.description = "Explain dependency compatibility for a build configuration";
      };
      gen-clangd = {
        type = "app";
        program = "${genClangd}/bin/gen-clangd";
        meta.description = "Generate the repository clangd configuration";
      };
      gen-nvim = {
        type = "app";
        program = "${genNvim}/bin/gen-nvim";
        meta.description = "Generate the repository Neovim configuration";
      };
      ccache = {
        type = "app";
        program = "${pkgs.ccache}/bin/ccache";
        meta.description = "Run ccache from the pinned development toolchain";
      };
      check-sdk = {
        type = "app";
        program = "${checkSdk}/bin/check-sdk";
        meta.description = "Inspect external input ELF dependencies";
      };
      update-cuda-catalog = {
        type = "app";
        program = "${updateCudaCatalog}/bin/update-cuda-catalog";
        meta.description = "Update exact CUDA redistributable catalog entries";
      };
      zigrad-build = {
        type = "app";
        program = pkgs.lib.getExe zigradBuild;
        meta.description = "Inspect Zigrad build configurations";
      };
    };

    checks.dependency-planner = dependencyPlannerTests;
  };
}
