# Repository development tools that are not Zigrad build configurations.
{
  perSystem = {
    pkgs,
    config,
    ...
  }: let
    cudaToolkit = config.packages.cuda-redist-dev;
    genClangd = pkgs.writeShellScriptBin "gen-clangd" ''
      set -euo pipefail

      root="$(${pkgs.lib.getExe pkgs.git} rev-parse --show-toplevel)"
      printf 'Generating .clangd root=%s\n' "$root"

      tmp="$(mktemp)"
      cat > "$tmp" <<EOF
      CompileFlags:
        CompilationDatabase: build
        Add:
          - -I${cudaToolkit}/include
          - -xcuda
          - --cuda-path=${cudaToolkit}
          - --no-cuda-version-check
        Remove:
          - -forward-unknown-to-host-compiler

      Diagnostics:
        UnusedIncludes: None
        MissingIncludes: None
      EOF

      mv "$tmp" "$root/.clangd"
      printf 'Wrote %s/.clangd\n' "$root"
    '';

    genNvim = pkgs.writeShellScriptBin "gen-nvim" ''
      set -euo pipefail

      root="$(${pkgs.lib.getExe pkgs.git} rev-parse --show-toplevel)"
      tmp="$(mktemp)"
      cat > "$tmp" <<EOF
      -- generated by nix/flake/tools.nix. do not edit.

      vim.lsp.config["zls"] = {
        cmd = { "${pkgs.zls}/bin/zls" },
        root_marker = { "build.zig", ".git" },
        filetypes = { "zig" },
      }

      vim.lsp.enable("zls")
      EOF

      mv "$tmp" "$root/.nvim.local.lua"
      printf 'Wrote %s/.nvim.local.lua\n' "$root"
    '';

    checkSdkPython = pkgs.python3.withPackages (pythonPackages: [
      pythonPackages.pyelftools
    ]);

    checkSdk = pkgs.writeShellApplication {
      name = "check-sdk";
      runtimeInputs = [checkSdkPython];
      text = ''
        exec python3 ${../../scripts/check_sdk.py} "$@"
      '';
    };

    resolveVersions = pkgs.writeShellApplication {
      name = "resolve-versions";
      runtimeInputs = [pkgs.git pkgs.python3];
      text = ''
        exec python3 ${../../scripts/resolve-versions.py} "$@"
      '';
    };
  in {
    packages = {
      check-sdk = checkSdk;
      gen-clangd = genClangd;
      gen-nvim = genNvim;
      resolve-versions = resolveVersions;
    };

    apps = {
      gen-clangd = {
        type = "app";
        program = "${genClangd}/bin/gen-clangd";
        meta.description = "Generate the repository clangd configuration";
      };
      gen-nvim = {
        type = "app";
        program = "${genNvim}/bin/gen-nvim";
        meta.description = "Generate the repository Neovim configuration";
      };
      ccache = {
        type = "app";
        program = "${pkgs.ccache}/bin/ccache";
        meta.description = "Run ccache from the pinned development toolchain";
      };
      check-sdk = {
        type = "app";
        program = "${checkSdk}/bin/check-sdk";
        meta.description = "Inspect external input ELF dependencies";
      };
      resolve-versions = {
        type = "app";
        program = "${resolveVersions}/bin/resolve-versions";
        meta.description = "Resolve a candidate external dependency set";
      };
    };
  };
}
