name: Format Check
on:
  pull_request:
  workflow_dispatch:
    inputs:
      zig-version:
        description: 'Zig version to use'
        required: false
        default: '0.14.0'

concurrency:
  group: zig-cache-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-format:
    runs-on: ubuntu-latest
    env:
      ZIG_VERSION: ${{ inputs.zig-version || '0.14.0' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
          use-cache: true
          cache-key: zig-global-${{ runner.os }}-${{ env.ZIG_VERSION }}
          cache-size-limit: 2048

      - name: Check formatting
        run: |
          find . -name '*.zig' -exec zig fmt --check {} +
          if [ $? -ne 0 ]; then
            echo "[X] Code must be formatted using 'zig fmt'. Please run it locally and commit the changes."
            exit 1
          fi
