name: Rebuild Docs and Update Tar
on:
  push:
    branches:
     - main
  workflow_dispatch:
    inputs:
      zig-version:
        description: 'Zig version to use'
        required: false
        default: '0.13.0'

permissions:
  contents: write

jobs:
  create-tar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ inputs.zig-version || '0.13.0' }}

      - name: Build docs
        run: |
          zig build docs

      - name: Switch branches and update tar
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |
          git config --global user.name "$GIT_AUTHOR_NAME"
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          cp ./zig-out/docs/sources.tar sources.tar
          git checkout gh-pages
          git add sources.tar
          git commit -m "Update source files tar"
          git push origin gh-pages
