name: Rebuild Docs and Update Tar
on:
  push:
    branches:
     - main
  schedule:
    - cron: '0 3 * * 0' # keep cache fresh
  workflow_dispatch:
    inputs:
      zig-version:
        description: 'Zig version to use'
        required: false
        default: '0.14.0'

permissions:
  contents: write

concurrency:
  group: zig-cache-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-tar:
    runs-on: ubuntu-latest
    env:
      ZIG_VERSION: ${{ inputs.zig-version || '0.14.0' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install OpenBLAS
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
          use-cache: true
          cache-key: zig-global-${{ runner.os }}-${{ env.ZIG_VERSION }}
          cache-size-limit: 2048

      - name: Build docs
        env:
          ZIGRAD_BACKEND: HOST
        run: |
          zig build docs

      - name: Switch branches and update tar
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |
          git config --global user.name "$GIT_AUTHOR_NAME"
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git checkout gh-pages
          mv -f zig-out/docs/sources.tar .
          git add sources.tar

          # Only commit if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "Update source files tar"
            git push origin gh-pages
          else
            echo "No changes in sources.tar to commit"
          fi
